# Default initial positions for h2017_with_delto_gripper's ros2_control fake system

initial_positions:
  F1M1: 0
  F1M2: 0
  F1M3: 0
  F1M4: 0
  F2M1: 0
  F2M2: 0
  F2M3: 0
  F2M4: 0
  F3M1: 0
  F3M2: 0
  F3M3: 0
  F3M4: 0
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0