# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_trajectory_controller
    - gripper_action_controller

  arm_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: follow_joint_trajectory
    default: true
  gripper_action_controller:
    type: GripperCommand
    joints:
      - F1M1
      - F1M2
      - F1M3
      - F1M4
      - F2M1
      - F2M2
      - F2M3
      - F2M4
      - F3M1
      - F3M2
      - F3M3
      - F3M4
    action_ns: gripper_cmd
    default: true