# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_action_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_action_controller:
  ros__parameters:
    joints:
      - F1M1
      - F1M2
      - F1M3
      - F1M4
      - F2M1
      - F2M2
      - F2M3
      - F2M4
      - F3M1
      - F3M2
      - F3M3
      - F3M4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
